version: "3.9"

services:
  composer:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: symfony_composer
    restart: always
    expose:
      - 9000
    command: /bin/sh -c "php-fpm"
    volumes:
      - "./:/var/www/symfony"
    networks:
      - back

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: symfony_nginx
    restart: always
    ports:
      - "${SERVER_PORT:-80}:80"
    volumes:
      - "./public:/var/www/symfony/public"
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - composer
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - back

  db:
    image: "mysql:latest"
    platform: linux/amd64 # For computers using an M1 chip
    container_name: symfony_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    expose:
      - 3306
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - back

volumes:
  mysql:

networks:
  back:
    driver: bridge
